### PR TITLE
User data ab test

### PR DESCRIPTION
**Pull request by edlt1611**
This notebook is a first pass at experiment design using the user data.

### CODE REVIEW

**Comment by janrito** [comment]
For reference, this is the file that i'm commenting on:
https://github.com/EDITD/research/blob/3578eee92029c210a3f3708d717a8c96d3009f9d/Ab_testing_user_data.ipynb

Overview is really good and clear. I especially like that you've set clearly what the purpose of the method is, and how we assess it. (nit-picky detail, I found a typo in the second paragraph, _deisgn_, might be worth checking for others)

**Query**:  (and also in general about the sections) It would be good to have a short description of what data you are querying here and where it's coming from

**To Pandas...**: I understand that you are creating a "session" here by looking at two points in time where a user was active, but i don't know how you've chosen them or what assumptions you are making. 

**Monte Carlo**: there are two `random_selection` functions, i'm not sure what the difference between them is.

**Final plot**: this comment will show my ignorance of the method, but It looks like you've concluded that any effect in the data is not large enough to allow us to differentiate between the test group and the control. I'd like to know more about how you read that from the results. 

This is an awesome start to the research repo @edlt1611! 
If we slowly add more like this, we'll have a nice library of relevant methods :)

**Comment by edlt1611** [comment]
Thanks for the comments @janrito. I have reread the text through to check for any typos.

Query/pandas: I have added a small paragraph discussing the data I have used. Hope this is a sufficient explanation. 

Monte Carlo: Ahh yeh I originally put the first in to split the data and find the mean of the set but this is done in the monte carlo loop so is no longer needed. I have removed the unused code

Final Plot: Yeh thats the case the sensitivity is too low. Our false positive rate is ok thats the lower red line. We want our initial data points to be below it and as you can see they are. The second higher red line points out our acceptable false negative rate 95% (as discussed at the top we could be more relaxed about this if we were at a push but should start at 95%). 

At the 95% mark this is where we know with confidence that we will detect a change to the B group. Our line hits this mark at a 6.5 minute change. which seeing as the mean of this set is 26mins this is a substantial change and it is unlikely any experiment we will ever run will make such a dramatic change. Therefore this isn't currently sensitive enough. Happy to talk more about this in person if you want?

**Comment by Jberrz** [comment]
Nice first commit @edlt1611! Interesting top level exploration of user data and the most experiment design we've done at EDITED to data 😅. I wish Github had a better way to comment on notebooks (allow us to comment directly on rendered notebook!) but I've left some general comments below.

Overall though really informative and like the approach taken.

**Typo/Grammar**
- First sentence grammar “This notebook is shows…” unneeded "is"
- Typo “substation” instead of “substantial” when discussing SD

**Code**
Some of your code is quite difficult to read. It might be good to add some inline comments or breakout and format your code a bit. e.g. 
```
session_data_dict = {}
for dict1 in output['rd']['session']['buckets']:
    
    session_data_dict.update({dict1['key']:{ 'min': dict1['upone']['mintime']['value_as_string'], 'max': dict1['upone']['maxtime']['value_as_string'], "account_info":dict1['upone']['doc_count'] }})
```
Could be made more readable like:
```
session_data_dict = {
        dict1[“key”]: {
            “min”: dict1[“upone”][“mintime”][“value_as_string”],
            “max": dict1[“upone”][“maxtime”][“value_as_string”],
            “account_info”: dict1[“upone”][“doc_count”], 
        }
       for dict1 in output['rd']['session']['buckets']
    }
```

**Discussion**
- As @janrito points out some explanation of the data you’re querying, and the assumptions you’ve made to define the concept of “session length” would be good.
-Really like that you’ve added docstrings to your functions!
- I’d like to see a short interpretation of the graph at the end too. I know you present your findings in results, but would be good to get a direct interpretation of the data on the graph.

**Comment by rkhood** [comment]
Enjoyed reading the notebook @edlt1611 !

One additional thing that might be good is to write a short paragraph on t-testing in the first or second section, e.g. its formula, 1-tail vs 2-tail, critical values etc.  This might help in producing the source of DS metrics we were talking about?

Also some further analysis of the plot at the end would be interesting!

Minor comments:
- You do not use the function "add_mean_to_sample"
- Monte Carlo should be capitalised
- In the first paragraph of results: "there was less that", should this be "there was less than a" ?
- After In [528] "After reviewing the data it appears the standard deviation is substation with a large maximum" - what do you mean by "substation"?
- penultimate paragraph has a couple of typos: should be "that's", "said we want" and "our line"

**Comment by risktoparkrageram** [comment]
Looks good! I think that it will be exciting to get stuck into some of this, and whilst you say the experiment isn't sensitive enough in this form - I think that it would definitely be possible to make something work with different metrics (perhaps at a less macro-level than overall session length for all users?). I would definitely be interested to see other metrics tested, and think it should definitely be factored into the work on user insights.

I think that the other comments around defining the  data being queried - what assumptions have been made around the definition of `sessions` (for example) highlight a key issue with the user data, and this is one that we have discussed previously - variables are logged, but they are not well documented. 

For instance, sessions are given IDs, but nowhere is it documented what logic is used to determine when sessions start or end. We can assume that they start on login, and end at logout, or after a set time when the browser is closed, but then we still have only a partial / speculative explanation for some sessions that appear to be far longer than we would expect - days or weeks long sessions... _a user has left the computer on with EDITED open in the browser? There was some bug in how the log off event was logged? something else?_

But a great first go at this, and points us in the right direction for the future - these are totally solve-able issues and this shows we can do some interesting analysis that will increase rigour in terms of how we think about the performance of app improvements.

**Comment by edlt1611** [comment]
Thanks everyone for your comments. Especially those on grammar and typos (I'm dyslexic so mostly don't see them so please keep em coming).

I think I have added all the changes people have requested so will probably close this now. There has been chat about discussing this more in person, I think @rkhood is setting something up so drop in if you're interested in chatting more about it. 

@risktoparkrageram I agree perhaps this was to macro for a first past. The work discussed around the user data and list will be a good opportunity to try out some more experiment design.

**Pull request merged**
